---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: solder-blue
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-cosmic
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - install-jb-xkb.sh
      - install-brother-hl3070cw-ppd.sh

  - type: dnf
    repos:
      copr:
        - jdxcode/mise
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
    install:
      packages:
        - mise
        - tailscale
        - kitty
        - gcc
        - gcc-c++
        - make
    remove:
      packages:
        - firefox
        - firefox-langpacks

  - type: systemd
    system:
      enabled:
        - tailscaled.service

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe
          - com.brave.Browser
          - com.slack.Slack
          - com.discordapp.Discord
          - org.signal.Signal
          - md.obsidian.Obsidian
          - org.libreoffice.LibreOffice
          - it.mijorus.gearlever
      - scope: user

  - type: fonts
    fonts:
      url-fonts:
        - name: MapleMono-NF
          url: https://github.com/subframe7536/maple-font/releases/latest/download/MapleMono-NF.zip

  - type: chezmoi
    repository: https://github.com/justyn/dotfiles
    branch: main
    file-conflict-policy: replace

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
